#!/bin/sh


#echo "Run with GOMAXPROCS=3 and GOMEMLIMIT=64MiB"
#GOMAXPROCS=3 GOMEMLIMIT=64MiB richgo test -count=1 -v -cover ./...

#echo "Run with GOMAXPROCS=3 and GOMEMLIMIT=128MiB"
#GOMAXPROCS=3 GOMEMLIMIT=128MiB richgo test -count=1 -v -cover ./...

#echo "Run with GOMAXPROCS=3 and GOMEMLIMIT=256MiB"
#GOMAXPROCS=3 GOMEMLIMIT=256MiB GODEBUG=gctrace=1 richgo test -count=1 -v -cover ./...

echo "Run with GOMAXPROCS=3 and GOMEMLIMIT=256MiB"
GOMAXPROCS=3 GOMEMLIMIT=256MiB GOGC=800 richgo test -count=1 -v -cover ./...